[package]
name = "graph"
version = "0.1.0"
authors = ["Martin Junghanns <nerdfaktor42@mailbox.org>"]
description = "A graph representation designed for large-scale graph processing."
keywords = ["graph", "csr", "algorithms"]
edition = "2018"
license = "MIT"

[dependencies]
num = "0.4"
thiserror = "1.0.24"
