[package]
name = "graph"
version = "0.1.0"
authors = [
    "Martin Junghanns <nerdfaktor42@mailbox.org>",
    "Paul Horn <developer@knutwalker.de>",
]
description = "A graph representation designed for large-scale graph processing."
keywords = ["graph", "csr", "algorithms"]
edition = "2018"
license = "MIT"

[dependencies]
atoi = "0.4.0"
delegate = "0.6.1"
linereader = "0.4.0"
log = "0.4.14"
memmap2 = "0.3.0"
num = "0.4"
num-format = "0.4.0"
num_cpus = "1.13.0"
page_size = "0.4.2"
rayon = "1.5.1"
thiserror = "1.0.24"

[dev-dependencies]
atomic_float = "0.1.0"
env_logger = "0.9.0"
num-format = "0.4.0"
pico-args = "0.4.0"

[features]
dotgraph_input = []
node_labeled_graph = ["dotgraph_input"]
