[package]
name = "graph"
version = "0.1.0"
authors = ["Martin Junghanns <nerdfaktor42@mailbox.org>"]
description = "A graph representation designed for large-scale graph processing."
keywords = ["graph", "csr", "algorithms"]
edition = "2018"
license = "MIT"

[lib]
name = "graph"
path = "src/lib.rs"

[[bin]]
name = "graph-app"
path = "src/bin.rs"

[dependencies]
atoi = "0.4.0"
linereader = "0.4.0"
num = "0.4"
num-format = "0.4.0"
rayon = "1.5.1"
thiserror = "1.0.24"
