[package]
name = "graph"
version = "0.1.14"
authors = [
    "Martin Junghanns <github@s1ck.dev>",
    "Paul Horn <developer@knutwalker.de>",
]
description = "A library of high-performant graph algorithms."
keywords = ["graph", "algorithms", "parallel"]
repository = "https://github.com/s1ck/graph"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_float = "0.1.0"
float-ord = "0.3.2"
graph_builder = { path = "../builder", version = "^0.1.0" }
log = "0.4.14"
num-format = "0.4.0"
rayon = "1.5.1"

[dev-dependencies]
graph_builder = { path = "../builder", version = "^0.1.0", features = ["gdl"] }
