[package]
name = "graph_server"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "8.0.0"
arrow-flight = "8.0.0"
async-trait = "0.1.36"
futures = "0.3.19"
graph = { path = "../algos", version = "^0.1.0", features = ["serde"] }
itertools = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.0"
tonic = "0.6"
